In [1]:
import os
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,mean_absolute_percentage_error

In [3]:
os.getcwd()
os.chdir(r"F:\DataScience")

In [6]:
df=pd.read_excel("Mtcars_With_Labels_32_Records.Xlsx",sheet_name="mtcars_raw")

In [7]:
df.head()

               model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [9]:
df.shape

(32, 12)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     str
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), str(1)
memory usage: 3.5 KB

In [11]:
df.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='str')

In [15]:
y=df['mpg']

In [17]:
X=df.drop(['mpg','model'],axis=1)

In [18]:
X.head()

   cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [19]:
X.isnull().sum()

cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [20]:
y.isnull().sum()

np.int64(0)

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42,shuffle=True)

In [25]:
model=LinearRegression()

In [26]:
model.fit(X_train,y_train)

LinearRegression()

In [30]:
model.coef_

array([-0.4762499 ,  0.01831107, -0.00950031,  1.00213048, -4.86203707,
        1.84095198, -1.93718579,  1.07662425,  1.32710759,  0.14713125])

In [31]:
model.intercept_

np.float64(-5.593700289851547)

In [88]:
y_train_predict=model.predict(X_train)
y_test_predict=model.predict(X_test)

In [90]:
print(y_train_predict)
print(y_test_predict)

[27.39049768 15.70105242 21.87895895 17.56562387 10.3566258  20.02980825
 16.19433136 13.67976942 12.68424241 21.6700726  25.02876011 26.62459558
 20.66251034 15.97812991 26.7722456  17.31748831 29.3183077  23.26753774
 24.53060883 23.27102515 19.40590412 12.37227519 18.32622956 29.72279449
 14.45060462]
[19.83092709 10.98714165 16.3140211  27.14590717 28.61321199 18.30133293
 14.88251095]

In [79]:

### For test metrics
mse_test=mean_squared_error(y_test,y_test_predict)
rmse_test=np.sqrt(mse_test)
mae_test=mean_absolute_error(y_test,y_test_predict)
mape_test=mean_absolute_percentage_error(y_test,y_test_predict)

print("mse_test:",mse_test)
print("rmse_test:",rmse_test)
print("mae_test:",mae_test)
print("mape_test:",mape_test)

mse_test: 10.13015466778728
rmse_test: 3.1827903901745214
mae_test: 2.24107265366749
mape_test: 0.09788290728392914

In [48]:
## For train metrics
mse_train=mean_squared_error(y_train,y_train_predict)
rmse_train=np.sqrt(mse_train)
mae_train=mean_absolute_error(y_train,y_train_predict)
mape_train=mean_absolute_percentage_error(y_train,y_train_predict)

print("mse_train:",mse_train)
print("rmse_train:",rmse_train)
print("mae_train:",mae_train)
print("mape_train:",mape_train)

mse_train: 4.22573616555623
rmse_train: 2.0556595451475497
mae_train: 1.6932642245436285
mape_train: 0.0895656495814097

In [94]:
print(type(model.coef_))     #numpy.ndarray can't directly write in to excel  : so convert int o data frames
print(type(X_train))         #pandas.DataFrame can write directly to array
print(type(X_test))


#m is the coefficient (also called the slope or weight in ML terms).
#y=(m1x1)+(m2x2)+...+c
#m1x1,mx2,... are coefficients
#Coefficient(s): The values multiplying your input features (x). They show how much the output changes when the input changes.
#(c=intercept)
#model_coef_df = pd.DataFrame({'Features':X.columns,'Model Coefficients':model.coef_})
df_model_coefs= pd.DataFrame({'Features':X.columns,'Coefficients:':model.coef_})  
df_intercept=pd.DataFrame({'Intercept:':[model.intercept_]})
df_train_metrics=pd.DataFrame({'Metrics':['mse','rmse','mae','mape'],
                      'Values' :[mse_train,rmse_train,mae_train,mape_train]
                      })
df_train_metrics=pd.DataFrame({'Metrics':['mse','rmse','mae','mape'],
                      'Values' :[mse_train,rmse_train,mae_train,mape_train]
                      })
df_test_metrics=pd.DataFrame({'Metrics':['mse','rmse','mae','mape'],
                      'Values' :[mse_test,rmse_test,mae_test,mape_test]
                      })
print("df_model_coefs:",df_model_coefs)
print("df_intercept:",df_intercept)
print("df_train_metrics:",df_train_metrics)
print("df_test_metrics:",df_test_metrics)

<class 'numpy.ndarray'>
<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
df_model_coefs:   Features  Coefficients:
0      cyl      -0.476250
1     disp       0.018311
2       hp      -0.009500
3     drat       1.002130
4       wt      -4.862037
5     qsec       1.840952
6       vs      -1.937186
7       am       1.076624
8     gear       1.327108
9     carb       0.147131
df_intercept:    Intercept:
0     -5.5937
df_train_metrics:   Metrics    Values
0     mse  4.225736
1    rmse  2.055660
2     mae  1.693264
3    mape  0.089566
df_test_metrics:   Metrics     Values
0     mse  10.130155
1    rmse   3.182790
2     mae   2.241073
3    mape   0.097883

In [95]:
#In excel to get like this :X(x1,x2..x10),y(mpg),Predict
#cyl	disp	hp	drat	wt	qsec	vs	am	gear	carb	mpg	Y_Test_Pred
#cyl	disp	hp	drat	wt	qsec	vs	am	gear	carb	mpg	Y_Train_Pred
y_train_pred_df = pd.DataFrame(
    {'Y_Train_Predict': y_train_predict},
    index=y_train.index
)
X_train_final= pd.concat([X_train,y_train,y_train_pred_df],axis=1)


y_test_pred_df=pd.DataFrame(
    {'Y_test_Predict':y_test_predict} ,
    index=y_test.index)

X_test_final=pd.concat([X_test,y_test,y_test_pred_df],axis=1)

In [96]:
## Create a Book Sheet for excel
with pd.ExcelWriter("Multiple_regression_19092026.xlsx",engine="xlsxwriter") as writer:
     df.to_excel(writer,sheet_name="RawData",index=True)
     X_train_final.to_excel(writer,sheet_name="TrainingData",index=False)
     X_test_final.to_excel(writer,sheet_name="TestingData",index=True)
     df_model_coefs.to_excel(writer,sheet_name="Coefficients",index=True)
     df_intercept.to_excel(writer,sheet_name="Intercept",index=True)
     df_train_metrics.to_excel(writer,sheet_name="Metrics in Train",index=True)
     df_test_metrics.to_excel(writer,sheet_name="Metrics in Test",index=True)